#!/usr/bin/env python3
"""Regenerate `chat4000_hermes_plugin/telemetry_dsn_generated.py`.

Idempotent. Run when rotating the Sentry DSN:

    CHAT4000_SENTRY_DSN="https://...@sentry.io/..." python3 scripts/prepare_release.py

With no env var set, falls back to the DSN already on disk (no-op) or
errors out if the file doesn't exist yet.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TARGET = REPO_ROOT / "chat4000_hermes_plugin" / "telemetry_dsn_generated.py"


def main() -> int:
    dsn = os.environ.get("CHAT4000_SENTRY_DSN", "").strip()
    if not dsn:
        if TARGET.exists():
            print(f"no CHAT4000_SENTRY_DSN set; leaving {TARGET.name} unchanged")
            return 0
        print("error: CHAT4000_SENTRY_DSN not set and target file missing", file=sys.stderr)
        return 1

    body = (
        '"""Sentry DSN for chat4000-hermes-plugin telemetry.\n\n'
        "Generated by scripts/prepare_release.py — committed to version control\n"
        "because Sentry DSNs are designed to be embedded in client code (they\n"
        "are public ingestion endpoints, not secret credentials).\n\n"
        "The DSN points at Sentry project `chat4000/chat4000-hermes-plugin`.\n"
        "Telemetry can still be disabled three ways: `hermes chat4000 telemetry\n"
        "disable`, `CHAT4000_TELEMETRY_DISABLED=1`, or `--no-telemetry`.\n"
        '"""\n\n'
        f'SENTRY_DSN = "{dsn}"\n'
    )
    TARGET.write_text(body, encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
