"""PostHog project credentials for chat4000-hermes-plugin.

Generated by scripts/prepare_release.py — committed to version control
because PostHog project API keys are designed to be embedded in client
code (write-only ingestion endpoints, not secret credentials).

Same PostHog project the iOS / macOS / CLI clients write to — events
get `source: hermes-plugin` (set in analytics.py) so they're filterable.

Opt out same as Sentry: `chat4000 telemetry disable`,
`CHAT4000_TELEMETRY_DISABLED=1`, or `--no-telemetry`.
"""

POSTHOG_API_KEY = "phc_s49DnTamyFDnEC6MyumNmmjjf7p455LXCVzPE94hPemZ"
POSTHOG_HOST = "https://us.i.posthog.com"
POSTHOG_PROJECT_ID = "393204"
