"""PostHog project credentials for chat4000-hermes-plugin.

Generated by scripts/prepare_release.py — committed to version control
because PostHog project API keys are designed to be embedded in client
code (write-only ingestion endpoints, not secret credentials).

Same PostHog project the iOS / macOS / CLI clients write to — events
get `source: hermes-plugin` (set in analytics.py) so they're filterable.

Opt out same as Sentry: `chat4000 telemetry disable`,
`CHAT4000_TELEMETRY_DISABLED=1`, or `--no-telemetry`.
"""

POSTHOG_API_KEY = "phc_wNRtzk3h5FTw2X6h4CvieEoxdSdqUd42eUqbgW6nD7B4"
POSTHOG_HOST = "https://posthog.chat4000.com"
POSTHOG_PROJECT_ID = ""  # self-hosted instance; numeric id not used for ingestion
