"""Sentry DSN for chat4000-hermes-plugin telemetry.

Generated by scripts/prepare_release.py — committed to version control
because Sentry DSNs are designed to be embedded in client code (they
are public ingestion endpoints, not secret credentials).

The DSN points at Sentry project `chat4000/chat4000-hermes-plugin`.
Telemetry can still be disabled three ways: `hermes chat4000 telemetry
disable`, `CHAT4000_TELEMETRY_DISABLED=1`, or `--no-telemetry`.
"""

SENTRY_DSN = "https://ac3dabffdf2c91c9c90a87cd9b258908@o4511305222193152.ingest.us.sentry.io/4511433133129728"
