"""Anonymous Sentry telemetry — on by default, easy to opt out.

Port of TS src/telemetry.ts. Same three opt-out paths:
  - `hermes chat4000 telemetry disable` (persistent)
  - `CHAT4000_TELEMETRY_DISABLED=1` env var
  - `--no-telemetry` CLI flag

Collects ONLY:
  - crash reports + stack traces
  - plugin version, Python version, OS platform/arch
  - anonymous install ID (UUID at ~/.config/chat4000/install-id)

Never sends message content, prompts, env vars, file paths with the
user's name, API keys, tokens, or PII.

The Sentry DSN is embedded at release-build time via
`src/telemetry_dsn_generated.py` (gitignored — generated by
scripts/prepare_release.py). Local dev runs have no DSN and are silent.
"""

from __future__ import annotations

import os
import re
import sys
import uuid
from pathlib import Path

from .package_info import read_package_version

PACKAGE_VERSION = read_package_version()
CONFIG_DIR = Path.home() / ".config" / "chat4000"
INSTALL_ID_PATH = CONFIG_DIR / "install-id"
TELEMETRY_ENABLED_PATH = CONFIG_DIR / "telemetry-enabled"


# ─── DSN loading ──────────────────────────────────────────────────────────


def _load_sentry_dsn() -> str | None:
    """Try the generated module first (release builds), then the env."""
    try:
        from . import telemetry_dsn_generated  # type: ignore[attr-defined]

        dsn = getattr(telemetry_dsn_generated, "SENTRY_DSN", None)
        if dsn:
            return str(dsn).strip()
    except ImportError:
        pass
    env_dsn = os.environ.get("CHAT4000_SENTRY_DSN", "").strip()
    return env_dsn or None


_SENTRY_DSN = _load_sentry_dsn()
_sentry_initialized = False


# ─── Public API ───────────────────────────────────────────────────────────


def get_telemetry_status(argv: list[str] | None = None) -> dict:
    """Returns dict with keys: enabled (bool), reason (str), install_id (str)."""
    argv = argv if argv is not None else sys.argv
    install_id = _resolve_install_id()
    if "--no-telemetry" in argv:
        return {"enabled": False, "reason": "flag", "install_id": install_id}

    env_var = os.environ.get("CHAT4000_TELEMETRY_DISABLED", "").strip().lower()
    if env_var in ("1", "true", "yes"):
        return {"enabled": False, "reason": "env", "install_id": install_id}

    if TELEMETRY_ENABLED_PATH.exists():
        try:
            value = TELEMETRY_ENABLED_PATH.read_text(encoding="utf-8").strip().lower()
            if value == "false":
                return {"enabled": False, "reason": "config", "install_id": install_id}
            if value == "true":
                return {"enabled": True, "reason": "config", "install_id": install_id}
        except OSError:
            pass

    return {"enabled": True, "reason": "default", "install_id": install_id}


def set_telemetry_enabled(enabled: bool) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    TELEMETRY_ENABLED_PATH.write_text("true\n" if enabled else "false\n", encoding="utf-8")
    try:
        os.chmod(TELEMETRY_ENABLED_PATH, 0o600)
    except OSError:
        pass


def initialize_chat4000_telemetry() -> None:
    """Lazy init Sentry on first telemetry-enabled run. Idempotent."""
    global _sentry_initialized
    if _sentry_initialized:
        return
    if _is_telemetry_control_command(sys.argv):
        return  # `hermes chat4000 telemetry status/enable/disable` should never start Sentry

    status = get_telemetry_status()
    if not status["enabled"]:
        return
    if not _SENTRY_DSN:
        return

    try:
        import sentry_sdk  # type: ignore[import-not-found]

        sentry_sdk.init(
            dsn=_SENTRY_DSN,
            release=f"chat4000-hermes-plugin@{PACKAGE_VERSION}",
            environment=os.environ.get("HERMES_ENV", "production"),
            sample_rate=0.2,
            traces_sample_rate=0.0,
            send_default_pii=False,
            attach_stacktrace=True,
            before_send=_scrub_event,
            default_integrations=False,
        )
        sentry_sdk.set_user({"id": status["install_id"]})
        sentry_sdk.set_tag("python_version", f"{sys.version_info.major}.{sys.version_info.minor}")
        sentry_sdk.set_tag("os_platform", sys.platform)
        sentry_sdk.set_tag("plugin_version", PACKAGE_VERSION)
        _sentry_initialized = True
    except Exception:
        # Telemetry must never break plugin startup.
        pass


def capture_chat4000_exception(error: BaseException, *, scope: str | None = None) -> None:
    if not _sentry_initialized:
        return
    try:
        import sentry_sdk  # type: ignore[import-not-found]

        with sentry_sdk.push_scope() as s:
            if scope:
                s.set_tag("chat4000_scope", _scrub_secrets(scope))
            sentry_sdk.capture_exception(error)
    except Exception:
        pass


# ─── Internals ────────────────────────────────────────────────────────────


def _is_telemetry_control_command(argv: list[str]) -> bool:
    """Detect `hermes chat4000 telemetry ...` invocations so we don't fire
    Sentry init while the user is mid-opt-out."""
    try:
        idx = argv.index("chat4000")
    except ValueError:
        return False
    return "telemetry" in argv[idx + 1 :]


def _resolve_install_id() -> str:
    try:
        if INSTALL_ID_PATH.exists():
            existing = INSTALL_ID_PATH.read_text(encoding="utf-8").strip()
            if existing:
                return existing
        new_id = str(uuid.uuid4())
        CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        INSTALL_ID_PATH.write_text(new_id + "\n", encoding="utf-8")
        try:
            os.chmod(INSTALL_ID_PATH, 0o600)
        except OSError:
            pass
        return new_id
    except Exception:
        return str(uuid.uuid4())


_SECRET_PATTERNS: list[tuple[re.Pattern, str]] = [
    (re.compile(r"sk-[a-zA-Z0-9]{20,}"), "[REDACTED_API_KEY]"),
    (re.compile(r"ghp_[a-zA-Z0-9]{20,}"), "[REDACTED_GITHUB_TOKEN]"),
    (re.compile(r"AKIA[0-9A-Z]{16}"), "[REDACTED_AWS_KEY]"),
    (re.compile(r"(?i)Bearer\s+[a-zA-Z0-9._-]+"), "Bearer [REDACTED]"),
    (re.compile(r"""(?i)password["\s:=]+[^\s",}]+"""), "password=[REDACTED]"),
    (re.compile(r"""(?i)token["\s:=]+[^\s",}]+"""), "token=[REDACTED]"),
]


def _scrub_secrets(text: str) -> str:
    out = text
    for pattern, replacement in _SECRET_PATTERNS:
        out = pattern.sub(replacement, out)
    return out


def _scrub_path(value: str) -> str:
    home = str(Path.home())
    if home and home in value:
        value = value.replace(home, "~")
    return re.sub(r"/(Users|home)/[^/]+", r"/\1/<user>", value)


def _scrub_event(event: dict, hint: dict) -> dict | None:
    """Sentry beforeSend hook — strips PII before send."""
    try:
        for exception in (event.get("exception") or {}).get("values", []) or []:
            if exception.get("value"):
                exception["value"] = _scrub_secrets(exception["value"])
            for frame in (exception.get("stacktrace") or {}).get("frames", []) or []:
                if frame.get("filename"):
                    frame["filename"] = _scrub_path(frame["filename"])
                frame.pop("vars", None)
        if event.get("message"):
            event["message"] = _scrub_secrets(event["message"])
        for key in ("env", "argv", "argv0"):
            (event.get("extra") or {}).pop(key, None)
        contexts = event.get("contexts") or {}
        (contexts.get("runtime") or {}).pop("env", None)
        (contexts.get("os") or {}).pop("kernel_version", None)
        return event
    except Exception:
        return event
