"""Sentry DSN for chat4000-hermes-plugin telemetry.

Generated by scripts/prepare_release.py — committed to version control
because Sentry DSNs are designed to be embedded in client code (they
are public ingestion endpoints, not secret credentials).

The DSN points at Sentry project `chat4000/chat4000-hermes-plugin`.
Telemetry can still be disabled three ways: `hermes chat4000 telemetry
disable`, `CHAT4000_TELEMETRY_DISABLED=1`, or `--no-telemetry`.
"""

SENTRY_DSN = "https://41cf740535c8a5a722cc1a13f090ea8d@sentry.chat4000.com/2"
